name: Build Vite React App on Merge

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Vite React App
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vite-react-build
          path: dist

      - name: Notify Google Chat
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"text": "Vite React App build complete. Artifacts have been uploaded."}' \
          ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
